/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/**
 * Dialogue versus narration, overall and per section, plus every quoted line
 * with its tag classified.
 */
export declare function analyzeDialogue(text: string, options?: FormatOptions | undefined | null): DialogueReport

/** Sentence-length flow: monotonous runs and overlong sentences. */
export declare function analyzeRhythm(text: string, options?: RhythmOptions | undefined | null): RhythmReport

export interface Attribution {
  dialogue: Location
  tag?: Location
  /** `plain` (said/asked), `showy` (exclaimed, snapped), or null when untagged. */
  kind?: string
  /** Whether the tag carries an adverb ("she said softly"). */
  adverb: boolean
  speaker?: string
}

/**
 * Flag adverbs, filter words, hedges and intensifiers, clichés, personal
 * tics, passive constructions, and nominalizations, each with its location.
 */
export declare function checkStyle(text: string, options?: StyleOptions | undefined | null): StyleReport

export interface Counts {
  words: number
  characters: number
  charactersNoSpaces: number
  sentences: number
  paragraphs: number
  readingMinutes: number
  speakingMinutes: number
}

export interface DialogueRatio {
  dialogueWords: number
  narrationWords: number
  /** Share of words inside quotation marks, 0..1. */
  ratio: number
}

export interface DialogueReport {
  ratio: DialogueRatio
  bySection: Array<SectionDialogue>
  attributions: Array<Attribution>
  plainTags: number
  showyTags: number
  adverbTags: number
  untagged: number
}

export interface Distribution {
  count: number
  mean: number
  median: number
  stdev: number
  min: number
  max: number
}

export interface Diversity {
  words: number
  unique: number
  /** Type-token ratio over the whole text. */
  ttr: number
  /** Moving-average type-token ratio, comparable across lengths. */
  mattr: number
  window: number
}

export interface Echo {
  word: string
  first: Location
  second: Location
  /** Words between the two uses. */
  distance: number
}

export interface EchoOptions {
  /** `"markdown"` (default), `"plain"`, or `"fountain"`. */
  format?: string
  /** Max words between two uses for them to count as an echo. Default 50. */
  window?: number
  /** Shortest word (in characters) to consider. Default 4. */
  minLength?: number
  /** Count capitalized names too. Default false. */
  includeNames?: boolean
  /** Words never to report. */
  ignore?: Array<string>
}

/** The same word reappearing within a window of words. */
export declare function findEchoes(text: string, options?: EchoOptions | undefined | null): Array<Echo>

/** Multi-word phrases that recur anywhere in the text, most frequent first. */
export declare function findRepeats(text: string, options?: RepeatOptions | undefined | null): Array<Repeat>

export interface FormatOptions {
  /** `"markdown"` (default), `"plain"`, or `"fountain"`. */
  format?: string
}

/**
 * Where something was found. `offset`/`length` are byte positions in the
 * text as given; `line`/`column` are 1-based.
 */
export interface Location {
  line: number
  column: number
  offset: number
  length: number
  /** Single-line excerpt of the span, middle-truncated when long. */
  excerpt: string
}

export interface Overused {
  word: string
  count: number
  documentPerMillion: number
  baselinePerMillion: number
  /** Document rate over baseline English rate. */
  ratio: number
}

export interface Readability {
  fleschReadingEase: number
  fleschKincaidGrade: number
  gunningFog: number
  colemanLiau: number
  automatedReadability: number
  words: number
  sentences: number
}

export interface Repeat {
  phrase: string
  words: number
  count: number
  locations: Array<Location>
}

export interface RepeatOptions {
  /** `"markdown"` (default), `"plain"`, or `"fountain"`. */
  format?: string
  /** Shortest phrase length in words. Default 3. */
  minWords?: number
  /** Longest phrase length in words. Default 6. */
  maxWords?: number
  /** Fewest occurrences to report. Default 2. */
  minCount?: number
}

/**
 * Everything at a glance for one text, matching `bluepencil report` with
 * default settings.
 */
export declare function report(text: string, options?: ReportOptions | undefined | null): Report

export interface Report {
  counts: Counts
  readability: Readability
  readabilityBySection: Array<SectionReadability>
  diversity: Diversity
  dialogue: DialogueRatio
  sentenceLengths: Distribution
  style: StyleCounts
  stylePerThousand: StyleRates
  echoes: number
  echoesPerThousand: number
  repeatedStarterRuns: number
  monotonousRuns: number
  longSentences: number
  topWords: Array<WordCount>
  topRepeats: Array<WordCount>
  topStarters: Array<WordCount>
  overused: Array<Overused>
}

export interface ReportOptions {
  /** `"markdown"` (default), `"plain"`, or `"fountain"`. */
  format?: string
  tics?: Array<string>
  /** How many top words, repeats, and overused words to include. Default 15. */
  top?: number
}

export interface RhythmOptions {
  /** `"markdown"` (default), `"plain"`, or `"fountain"`. */
  format?: string
  /** Consecutive sentences of similar length that count as monotonous. Default 4. */
  run?: number
  /** Word-count difference still considered "similar". Default 3. */
  tolerance?: number
  /** Sentence length (words) flagged as overlong. Default 40. */
  long?: number
}

export interface RhythmReport {
  /** Word count of every sentence, in order. */
  lengths: Array<number>
  summary: Distribution
  /** Stdev over mean; low values read as monotonous. */
  variation: number
  /** `monotony` runs and `long-sentence` findings. */
  findings: Array<StyleFinding>
}

/**
 * Pacing profile per section (heading): length, dialogue share, sentence
 * rhythm, and style density.
 */
export declare function sectionArc(text: string, options?: FormatOptions | undefined | null): Array<SectionArc>

export interface SectionArc {
  section: string
  words: number
  dialogueRatio: number
  sentenceWordsMean: number
  adverbs: number
  adverbsPer1K: number
  passive: number
  passivePer1K: number
}

export interface SectionDialogue {
  section: string
  ratio: DialogueRatio
}

export interface SectionReadability {
  title: string
  scores: Readability
}

/** How sentences and paragraphs open, and runs that open the same way. */
export declare function sentenceStarters(text: string, options?: StarterOptions | undefined | null): StarterReport

export interface StarterOptions {
  /** `"markdown"` (default), `"plain"`, or `"fountain"`. */
  format?: string
  /** Consecutive sentences opening with the same word to flag. Default 3. */
  run?: number
}

export interface StarterReport {
  /** Most common sentence-opening words. */
  sentence: Array<WordCount>
  /** Most common paragraph-opening words. */
  paragraph: Array<WordCount>
  /** `repeated-starter` runs. */
  findings: Array<StyleFinding>
}

export interface StyleCounts {
  adverbs: number
  filterWords: number
  hedges: number
  cliches: number
  tics: number
  passive: number
  nominalizations: number
}

/** A located observation a writer may want to act on. */
export interface StyleFinding {
  /**
   * `adverb`, `filter`, `hedge`, `cliche`, `tic`, `passive`, `nominal`,
   * `monotony`, `long-sentence`, or `repeated-starter`.
   */
  rule: string
  message: string
  location: Location
  inDialogue: boolean
}

export interface StyleOptions {
  /** `"markdown"` (default), `"plain"`, or `"fountain"`. */
  format?: string
  /** Extra words or phrases to flag as personal tics (`rule: "tic"`). */
  tics?: Array<string>
}

export interface StyleRates {
  adverbs: number
  filterWords: number
  hedges: number
  cliches: number
  tics: number
  passive: number
  nominalizations: number
}

export interface StyleReport {
  words: number
  counts: StyleCounts
  /** Each count per 1,000 words, so documents of different lengths compare. */
  perThousand: StyleRates
  /** Every finding in document order. */
  findings: Array<StyleFinding>
}

export interface WordCount {
  word: string
  count: number
}
